spring.application.name=AuthApp

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:10.43.7.9}:${MYSQL_PORT:3306}/${MYSQL_DB:authservice}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
#spring.datasource.username=root
#spring.datasource.password=ubuntu123_A


# JDBC URL
spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12800149
#spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12800149?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
# Database credentials
spring.datasource.username=sql12800149
spring.datasource.password=PJznT7VhCY

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update

server.port=9898

logging.level.org.springframework.security=DEBUG
logging.level.your.package.name=DEBUG